backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "artikel"
    label: "Artikel"
    folder: "artikel"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Isi", name: "body", widget: "markdown" }
