backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "artikel"
    label: "Artikel"
    folder: "artikel"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "kategori", widget: "select", options: ["nasional", "internasional", "healthy", "sport", "zodiak", "loker"] }
      - { label: "Gambar Utama", name: "thumbnail", widget: "image", required: false }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
